# transforming athlete csv file
---
- processing using pandas
- processing through csv methods and pickle transformation

In [2]:
import pandas as pd
import csv
import pickle

### test case 1
---
csv containing referee decision data

In [23]:

PATH = r"C:\Users\josed\projects\powerliftingCompHandler\powerliftingcomphandler\data\open_nationals_day_2_awards_results.csv"

df = pd.read_csv(PATH)
df.head()

ParserError: Error tokenizing data. C error: Expected 76 fields in line 4, saw 81

---
- issue: csv has values with delimeter within the value
- decision: using the sep perameter to seporate data without the , 
- status: pending
- group: data transformation
- assumptions: using pandas "sep" parameter to be able to obtain values through different sepration - method
- constraint: \t might not fix the issue 
- position: using pandas to be able to view data still might improve the transformation methods compared to other methods
- implications: data has "," inside of values as well as not meeting first normal form standards

In [71]:
df = pd.read_csv(
    PATH,
    sep="\t",
)

df.head()

  Name                , "Gender", "Raw/Equipped", "Team", "Lot", "State/Province", "Country", "Platform", "Session", "Flight", "Awards Division" , "Body Weight (kg)", "Weight Class", "Wilks Coef"        , "Exact Age", "Division Based Age", "Age Coef", "Squat 1", "Squat 2", "Squat 3", "Best Squat", "Bench 1", "Bench 2", "Bench 3", "Best Bench", "Subtotal", "Deadlift 1", "Deadlift 2", "Deadlift 3", "Best Deadlift", "Total", "Dots Points"       , "Dots & Age Points" , "Wilks Points"      , "Age Points"        , "Wilks & Age Points", "IPF Points"        , "IPF & Age Points"  , "Glossbrenner Points", "Glossbrenner & Age Points", "Schwartz Malone Points", "Schwartz Malone & Age Points", "Place", "S1LRef"  , "S1HRef"  , "S1RRef"           , "S2LRef"     , "S2HRef"     , "S2RRef"     , "S3LRef"     , "S3HRef"     , "S3RRef"     , "B1LRef"     , "B1HRef"   , "B1RRef"     , "B2LRef"     , "B2HRef"     , "B2RRef"     , "B3LRef"     , "B3HRef"           , "B3RRef"     , "D1LRef"     , "D1HRef"     , "D1RRef"     , "D2LRef"     , "D2HRef"     , "D2RRef"     , "D3LRef"     , "D3HRef"     , "D3RRef"
0  Meghan Scanlon      , "FEMALE", "RAW"         ...
1  Daisy Arreola Garcia, "FEMALE", "RAW"         ...
2  Hannah Peterson     , "FEMALE", "RAW"         ...
3  Sydney Hunter       , "FEMALE", "RAW"         ...
4  Maggie Stout        , "FEMALE", "RAW"         ...

In [72]:
df.columns

Index(['Name                , "Gender", "Raw/Equipped", "Team", "Lot", "State/Province", "Country", "Platform", "Session", "Flight", "Awards Division" , "Body Weight (kg)", "Weight Class", "Wilks Coef"        , "Exact Age", "Division Based Age", "Age Coef", "Squat 1", "Squat 2", "Squat 3", "Best Squat", "Bench 1", "Bench 2", "Bench 3", "Best Bench", "Subtotal", "Deadlift 1", "Deadlift 2", "Deadlift 3", "Best Deadlift", "Total", "Dots Points"       , "Dots & Age Points" , "Wilks Points"      , "Age Points"        , "Wilks & Age Points", "IPF Points"        , "IPF & Age Points"  , "Glossbrenner Points", "Glossbrenner & Age Points", "Schwartz Malone Points", "Schwartz Malone & Age Points", "Place", "S1LRef"  , "S1HRef"  , "S1RRef"           , "S2LRef"     , "S2HRef"     , "S2RRef"     , "S3LRef"     , "S3HRef"     , "S3RRef"     , "B1LRef"     , "B1HRef"   , "B1RRef"     , "B2LRef"     , "B2HRef"     , "B2RRef"     , "B3LRef"     , "B3HRef"           , "B3RRef"     , "D1LRef"     , "D1HRef"     , "D1RRef"     , "D2LRef"     , "D2HRef"     , "D2RRef"     , "D3LRef"     , "D3HRef"     , "D3RRef"'], dtype='str')

In [73]:
for i, col in enumerate(df.columns.str.split(',')[0]):
    print(col, " | ", i )

Name                  |  0
 "Gender"  |  1
 "Raw/Equipped"  |  2
 "Team"  |  3
 "Lot"  |  4
 "State/Province"  |  5
 "Country"  |  6
 "Platform"  |  7
 "Session"  |  8
 "Flight"  |  9
 "Awards Division"   |  10
 "Body Weight (kg)"  |  11
 "Weight Class"  |  12
 "Wilks Coef"          |  13
 "Exact Age"  |  14
 "Division Based Age"  |  15
 "Age Coef"  |  16
 "Squat 1"  |  17
 "Squat 2"  |  18
 "Squat 3"  |  19
 "Best Squat"  |  20
 "Bench 1"  |  21
 "Bench 2"  |  22
 "Bench 3"  |  23
 "Best Bench"  |  24
 "Subtotal"  |  25
 "Deadlift 1"  |  26
 "Deadlift 2"  |  27
 "Deadlift 3"  |  28
 "Best Deadlift"  |  29
 "Total"  |  30
 "Dots Points"         |  31
 "Dots & Age Points"   |  32
 "Wilks Points"        |  33
 "Age Points"          |  34
 "Wilks & Age Points"  |  35
 "IPF Points"          |  36
 "IPF & Age Points"    |  37
 "Glossbrenner Points"  |  38
 "Glossbrenner & Age Points"  |  39
 "Schwartz Malone Points"  |  40
 "Schwartz Malone & Age Points"  |  41
 "Place"  |  42
 "S1LRef"    |  43
 "S1HRef"    |  44
 "S1RRef"             |  45
 "S2LRef"       |  46
 "S2HRef"       |  47
 "S2RRef"       |  48
 "S3LRef"       |  49
 "S3HRef"       |  50
 "S3RRef"       |  51
 "B1LRef"       |  52
 "B1HRef"     |  53
 "B1RRef"       |  54
 "B2LRef"       |  55
 "B2HRef"       |  56
 "B2RRef"       |  57
 "B3LRef"       |  58
 "B3HRef"             |  59
 "B3RRef"       |  60
 "D1LRef"       |  61
 "D1HRef"       |  62
 "D1RRef"       |  63
 "D2LRef"       |  64
 "D2HRef"       |  65
 "D2RRef"       |  66
 "D3LRef"       |  67
 "D3HRef"       |  68
 "D3RRef"  |  69

In [74]:
df.info

<bound method DataFrame.info of    Name                , "Gender", "Raw/Equipped", "Team", "Lot", "State/Province", "Country", "Platform", "Session", "Flight", "Awards Division" , "Body Weight (kg)", "Weight Class", "Wilks Coef"        , "Exact Age", "Division Based Age", "Age Coef", "Squat 1", "Squat 2", "Squat 3", "Best Squat", "Bench 1", "Bench 2", "Bench 3", "Best Bench", "Subtotal", "Deadlift 1", "Deadlift 2", "Deadlift 3", "Best Deadlift", "Total", "Dots Points"       , "Dots & Age Points" , "Wilks Points"      , "Age Points"        , "Wilks & Age Points", "IPF Points"        , "IPF & Age Points"  , "Glossbrenner Points", "Glossbrenner & Age Points", "Schwartz Malone Points", "Schwartz Malone & Age Points", "Place", "S1LRef"  , "S1HRef"  , "S1RRef"           , "S2LRef"     , "S2HRef"     , "S2RRef"     , "S3LRef"     , "S3HRef"     , "S3RRef"     , "B1LRef"     , "B1HRef"   , "B1RRef"     , "B2LRef"     , "B2HRef"     , "B2RRef"     , "B3LRef"     , "B3HRef"           , "B3RRef"     , "D1LRef"     , "D1HRef"     , "D1RRef"     , "D2LRef"     , "D2HRef"     , "D2RRef"     , "D3LRef"     , "D3HRef"     , "D3RRef"
0   Meghan Scanlon      , "FEMALE", "RAW"         ...
1   Daisy Arreola Garcia, "FEMALE", "RAW"         ...
2   Hannah Peterson     , "FEMALE", "RAW"         ...
3   Sydney Hunter       , "FEMALE", "RAW"         ...
4   Maggie Stout        , "FEMALE", "RAW"         ...
..                                                ...
60  Benjamin Mathews    , "MALE"  , "RAW"         ...
61  Brandon Flores      , "MALE"  , "RAW"         ...
62  Manasseh Endwarrior , "MALE"  , "RAW"         ...
63  Hao Cheng           , "MALE"  , "RAW"         ...
64  Charles Hammonds    , "MALE"  , "RAW"         ...

[65 rows x 1 columns]>

In [75]:
SAMPLE = df['Name                , "Gender", "Raw/Equipped", "Team", "Lot", "State/Province", "Country", "Platform", "Session", "Flight", "Awards Division" , "Body Weight (kg)", "Weight Class", "Wilks Coef"        , "Exact Age", "Division Based Age", "Age Coef", "Squat 1", "Squat 2", "Squat 3", "Best Squat", "Bench 1", "Bench 2", "Bench 3", "Best Bench", "Subtotal", "Deadlift 1", "Deadlift 2", "Deadlift 3", "Best Deadlift", "Total", "Dots Points"       , "Dots & Age Points" , "Wilks Points"      , "Age Points"        , "Wilks & Age Points", "IPF Points"        , "IPF & Age Points"  , "Glossbrenner Points", "Glossbrenner & Age Points", "Schwartz Malone Points", "Schwartz Malone & Age Points", "Place", "S1LRef"  , "S1HRef"  , "S1RRef"           , "S2LRef"     , "S2HRef"     , "S2RRef"     , "S3LRef"     , "S3HRef"     , "S3RRef"     , "B1LRef"     , "B1HRef"   , "B1RRef"     , "B2LRef"     , "B2HRef"     , "B2RRef"     , "B3LRef"     , "B3HRef"           , "B3RRef"     , "D1LRef"     , "D1HRef"     , "D1RRef"     , "D2LRef"     , "D2HRef"     , "D2RRef"     , "D3LRef"     , "D3HRef"     , "D3RRef"'].replace(' ','').replace('"','')

In [76]:
SAMPLE[0]

'Meghan Scanlon      , "FEMALE", "RAW"         , ""    , "141", "MA"            ,          , "2"       , "4"      , "A"     , "Women\'s Raw Open", "62.74"           , "63"          , "1.0773287692485658", "37"       , "38"                , "1"       , "182.5"  , "195"    , "203.5"  , "203.5"     , "132.5"  , "137.5"  , "-143.5" , "137.5"     , "341"     , "192.5"     , "212.5"     , "222.5"     , "222.5"        , "563.5", "607.5830565145685" , "607.5830565145685" , "607.0747614715668" , "563.5"             , "607.0747614715668" , "123.61407916828898", "123.61407916828898", "536.942245"         , "536.942245"               , "467.8177"              , "467.8177"                    , "1"    , "good"    , "good"    , "good"             , "good"       , "good"       , "good"       , "good"       , "good"       , "good"       , "good"       , "bad, red" , "good"       , "bad, blue"  , "good"       , "good"       , "bad, yellow", "bad, yellow"      , "bad, yellow", "good"       , "bad, yellow", "good"       , "good"       , "good"       , "good"       , "good"       , "good"       , "good"'

In [35]:
# standardizing columns to make them easier to work with
COLS_RAW = df.columns.str.split(',')[0]
COLS = df.columns.str.replace(' ', '').str.replace('"', '').str.split(',')[0]
print(COLS)

['Name', 'Gender', 'Raw/Equipped', 'Team', 'Lot', 'State/Province', 'Country', 'Platform', 'Session', 'Flight', 'AwardsDivision', 'BodyWeight(kg)', 'WeightClass', 'WilksCoef', 'ExactAge', 'DivisionBasedAge', 'AgeCoef', 'Squat1', 'Squat2', 'Squat3', 'BestSquat', 'Bench1', 'Bench2', 'Bench3', 'BestBench', 'Subtotal', 'Deadlift1', 'Deadlift2', 'Deadlift3', 'BestDeadlift', 'Total', 'DotsPoints', 'Dots&AgePoints', 'WilksPoints', 'AgePoints', 'Wilks&AgePoints', 'IPFPoints', 'IPF&AgePoints', 'GlossbrennerPoints', 'Glossbrenner&AgePoints', 'SchwartzMalonePoints', 'SchwartzMalone&AgePoints', 'Place', 'S1LRef', 'S1HRef', 'S1RRef', 'S2LRef', 'S2HRef', 'S2RRef', 'S3LRef', 'S3HRef', 'S3RRef', 'B1LRef', 'B1HRef', 'B1RRef', 'B2LRef', 'B2HRef', 'B2RRef', 'B3LRef', 'B3HRef', 'B3RRef', 'D1LRef', 'D1HRef', 'D1RRef', 'D2LRef', 'D2HRef', 'D2RRef', 'D3LRef', 'D3HRef', 'D3RRef']

### transforming using limited table
---
- doesnt capture all data

In [78]:
REF_DECISION_INDEX = 40
NO_REFS_COLS = COLS_RAW[:REF_DECISION_INDEX]

NO_REFS_COLS

['Name                ',
 ' "Gender"',
 ' "Raw/Equipped"',
 ' "Team"',
 ' "Lot"',
 ' "State/Province"',
 ' "Country"',
 ' "Platform"',
 ' "Session"',
 ' "Flight"',
 ' "Awards Division" ',
 ' "Body Weight (kg)"',
 ' "Weight Class"',
 ' "Wilks Coef"        ',
 ' "Exact Age"',
 ' "Division Based Age"',
 ' "Age Coef"',
 ' "Squat 1"',
 ' "Squat 2"',
 ' "Squat 3"',
 ' "Best Squat"',
 ' "Bench 1"',
 ' "Bench 2"',
 ' "Bench 3"',
 ' "Best Bench"',
 ' "Subtotal"',
 ' "Deadlift 1"',
 ' "Deadlift 2"',
 ' "Deadlift 3"',
 ' "Best Deadlift"',
 ' "Total"',
 ' "Dots Points"       ',
 ' "Dots & Age Points" ',
 ' "Wilks Points"      ',
 ' "Age Points"        ',
 ' "Wilks & Age Points"',
 ' "IPF Points"        ',
 ' "IPF & Age Points"  ',
 ' "Glossbrenner Points"',
 ' "Glossbrenner & Age Points"']

In [83]:
df_ern = pd.read_csv(PATH, usecols=NO_REFS_COLS, sep=',', quotechar='"')
print(df_ern.columns.tolist())

['Name                ', ' "Gender"', ' "Raw/Equipped"', ' "Team"', ' "Lot"', ' "State/Province"', ' "Country"', ' "Platform"', ' "Session"', ' "Flight"', ' "Awards Division" ', ' "Body Weight (kg)"', ' "Weight Class"', ' "Wilks Coef"        ', ' "Exact Age"', ' "Division Based Age"', ' "Age Coef"', ' "Squat 1"', ' "Squat 2"', ' "Squat 3"', ' "Best Squat"', ' "Bench 1"', ' "Bench 2"', ' "Bench 3"', ' "Best Bench"', ' "Subtotal"', ' "Deadlift 1"', ' "Deadlift 2"', ' "Deadlift 3"', ' "Best Deadlift"', ' "Total"', ' "Dots Points"       ', ' "Dots & Age Points" ', ' "Wilks Points"      ', ' "Age Points"        ', ' "Wilks & Age Points"', ' "IPF Points"        ', ' "IPF & Age Points"  ', ' "Glossbrenner Points"', ' "Glossbrenner & Age Points"']

In [84]:
df_ern.info

<bound method DataFrame.info of                                                                            Name                  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"

                                                                               "Gender"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "2"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "2"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "2"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "2"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "2"
...                                                                                 ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "2"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "2"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "2"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "2"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "2"

                                                                            "Raw/Equipped"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                   "4"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                   "4"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                   "4"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"                   "4"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"                   "4"
...                                                                                    ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                   "3"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                   "3"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                   "3"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"                   "3"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"                   "4"

                                                                               "Team"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "A"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "A"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "A"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "A"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "A"
...                                                                               ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "A"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "A"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "A"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "A"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "B"

                                                                                          "Lot"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "Women's Raw Open"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "Women's Raw Open"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "Women's Raw Open"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "Women's Raw Open"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "Women's Raw Open"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "Men's Raw Open"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "Men's Raw Open"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "Men's Raw Open"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "Men's Raw Open"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "Men's Raw Open"

                                                                               "State/Province"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "62.74"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "61.74"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "62.58"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "61.2"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "62.56"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "81.72"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "81.18"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "82.14"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "80.68"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "82.04"

                                                                                  "Country"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "63"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "63"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "63"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "63"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "63"
...                                                                                     ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "83"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "83"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "83"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "83"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "83"

                                                                                       "Platform"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "1.0773287692485658"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "1.0906031673251644"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "1.0794197564496506"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "1.0979768059215098"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "1.079682006780528"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "0.6737597544301983"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "0.6764993508076719"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "0.671669887265663"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "0.6790899576347297"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0.6721642674003474"

                                                                               "Session"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "37"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "24"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "27"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "29"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "25"
...                                                                                  ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "27"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "21"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "28"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "30"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "30"

                                                                                         "Flight"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "38"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "25"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "28"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "30"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "26"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "27"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "22"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "29"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "31"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "31"

                                                                            ...  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"              ...
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"              ...
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"              ...
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"              ...
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"              ...
...                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"              ...
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"              ...
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"              ...
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"              ...
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"              ...

                                                                                          "Total"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "123.61407916828898"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "106.41284286028542"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "105.4715462023794"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "104.8100031030182"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "97.8012543819851"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "72.89908742335024"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "69.2951051782327"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "67.14361626070193"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "63.89589860472197"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                             "Dots Points"         \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "123.61407916828898"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "106.41284286028542"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "105.4715462023794"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "104.8100031030182"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "97.8012543819851"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "72.89908742335024"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "70.68100728179736"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "67.14361626070193"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "63.89589860472197"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                              "Dots & Age Points"   \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "536.942245"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "463.25759999999997"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "458.256"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "456.887"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "425.1085"
...                                                                                            ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "338.94575000000003"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "322.3935"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "311.888"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "297.57"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                    "Wilks Points"        \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "536.942245"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "463.25759999999997"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "458.256"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "456.887"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "425.1085"
...                                                                                                  ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "338.94575000000003"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "328.84137000000004"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "311.888"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "297.57"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                 "Age Points"          \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "467.8177"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "388.848"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "398.49600000000004"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "397.714"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "369.439"
...                                                                                               ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "325.9355"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "309.969"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "299.8255"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "286.104"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                       "Wilks & Age Points"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "467.8177"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "388.848"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "398.49600000000004"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "397.714"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "369.439"
...                                                                                                     ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "325.9355"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "316.16838"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "299.8255"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "286.104"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                            "IPF Points"          \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                           "1"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                           "2"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                           "3"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"                           "4"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"                           "5"
...                                                                                          ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                           "28"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                           "29"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                           "30"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"                           "31"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"                           ""

                                                                            "IPF & Age Points"    \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                        "good"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                        "good"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                        "good"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"
...                                                                                          ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                        "good"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                        "good"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                        "good"

In [85]:
df_ern.columns

Index(['Name                ', ' "Gender"', ' "Raw/Equipped"', ' "Team"',
       ' "Lot"', ' "State/Province"', ' "Country"', ' "Platform"',
       ' "Session"', ' "Flight"', ' "Awards Division" ', ' "Body Weight (kg)"',
       ' "Weight Class"', ' "Wilks Coef"        ', ' "Exact Age"',
       ' "Division Based Age"', ' "Age Coef"', ' "Squat 1"', ' "Squat 2"',
       ' "Squat 3"', ' "Best Squat"', ' "Bench 1"', ' "Bench 2"', ' "Bench 3"',
       ' "Best Bench"', ' "Subtotal"', ' "Deadlift 1"', ' "Deadlift 2"',
       ' "Deadlift 3"', ' "Best Deadlift"', ' "Total"',
       ' "Dots Points"       ', ' "Dots & Age Points" ',
       ' "Wilks Points"      ', ' "Age Points"        ',
       ' "Wilks & Age Points"', ' "IPF Points"        ',
       ' "IPF & Age Points"  ', ' "Glossbrenner Points"',
       ' "Glossbrenner & Age Points"'],
      dtype='str')

In [86]:
df_ern.iloc[0]

Name
 "Gender"                                            "2"
 "Raw/Equipped"                                       "4"
 "Team"                                                "A"
 "Lot"                                       "Women's Raw Open"
 "State/Province"                            "62.74"
 "Country"                                       "63"
 "Platform"                                "1.0773287692485658"
 "Session"                                          "37"
 "Flight"                                  "38"
 "Awards Division"                                   "1"
 "Body Weight (kg)"                                   "182.5"
 "Weight Class"                                       "195"
 "Wilks Coef"                                         "203.5"
 "Exact Age"                                       "203.5"
 "Division Based Age"                                 "132.5"
 "Age Coef"                                           "137.5"
 "Squat 1"                                            "-143.5"
 "Squat 2"                                         "137.5"
 "Squat 3"                                           "341"
 "Best Squat"                                      "192.5"
 "Bench 1"                                         "212.5"
 "Bench 2"                                         "222.5"
 "Bench 3"                                      "222.5"
 "Best Bench"                                           "563.5"
 "Subtotal"                                "607.5830565145685"
 "Deadlift 1"                              "607.5830565145685"
 "Deadlift 2"                              "607.0747614715668"
 "Deadlift 3"                              "563.5"
 "Best Deadlift"                           "607.0747614715668"
 "Total"                                   "123.61407916828898"
 "Dots Points"                             "123.61407916828898"
 "Dots & Age Points"                      "536.942245"
 "Wilks Points"                     "536.942245"
 "Age Points"                          "467.8177"
 "Wilks & Age Points"            "467.8177"
 "IPF Points"                                           "1"
 "IPF & Age Points"                                  "good"
 "Glossbrenner Points"                               "good"
 "Glossbrenner & Age Points"                "good"
Name: (Meghan Scanlon      ,  "FEMALE",  "RAW"         ,  ""    ,  "141",  "MA"            ), dtype: str

In [ ]:
REF_DECISION_INDEX = 40
NO_REFS_COLS = COLS_RAW[:REF_DECISION_INDEX]
df = pd.read_csv(PATH, usecols=NO_REFS_COLS)

df.head()

,,,,,,Name,"""Gender""","""Raw/Equipped""","""Team""","""Lot""","""State/Province""","""Country""","""Platform""","""Session""","""Flight""",...,"""Total""","""Dots Points""","""Dots & Age Points""","""Wilks Points""","""Age Points""","""Wilks & Age Points""","""IPF Points""","""IPF & Age Points""","""Glossbrenner Points""","""Glossbrenner & Age Points"""
Meghan Scanlon,"""FEMALE""","""RAW""","""""","""141""","""MA""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.74""","""63""","""1.0773287692485658""","""37""","""38""",...,"""123.61407916828898""","""123.61407916828898""","""536.942245""","""536.942245""","""467.8177""","""467.8177""","""1""","""good""","""good""","""good"""
Daisy Arreola Garcia,"""FEMALE""","""RAW""","""""","""138""","""OR""",,"""2""","""4""","""A""","""Women's Raw Open""","""61.74""","""63""","""1.0906031673251644""","""24""","""25""",...,"""106.41284286028542""","""106.41284286028542""","""463.25759999999997""","""463.25759999999997""","""388.848""","""388.848""","""2""","""good""","""good""","""bad"
Hannah Peterson,"""FEMALE""","""RAW""","""""","""140""","""MN""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.58""","""63""","""1.0794197564496506""","""27""","""28""",...,"""105.4715462023794""","""105.4715462023794""","""458.256""","""458.256""","""398.49600000000004""","""398.49600000000004""","""3""","""good""","""good""","""good"""
Sydney Hunter,"""FEMALE""","""RAW""","""""","""136""","""CA""",,"""2""","""4""","""A""","""Women's Raw Open""","""61.2""","""63""","""1.0979768059215098""","""29""","""30""",...,"""104.8100031030182""","""104.8100031030182""","""456.887""","""456.887""","""397.714""","""397.714""","""4""",,,
Maggie Stout,"""FEMALE""","""RAW""","""""","""137""","""MN""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.56""","""63""","""1.079682006780528""","""25""","""26""",...,"""97.8012543819851""","""97.8012543819851""","""425.1085""","""425.1085""","""369.439""","""369.439""","""5""",,,

In [37]:
df.info

<bound method DataFrame.info of                                                                            Name                  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"

                                                                               "Gender"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "2"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "2"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "2"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "2"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "2"
...                                                                                 ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "2"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "2"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "2"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "2"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "2"

                                                                            "Raw/Equipped"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                   "4"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                   "4"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                   "4"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"                   "4"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"                   "4"
...                                                                                    ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                   "3"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                   "3"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                   "3"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"                   "3"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"                   "4"

                                                                               "Team"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "A"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "A"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "A"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "A"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "A"
...                                                                               ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "A"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "A"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "A"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "A"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "B"

                                                                                          "Lot"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "Women's Raw Open"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "Women's Raw Open"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "Women's Raw Open"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "Women's Raw Open"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "Women's Raw Open"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "Men's Raw Open"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "Men's Raw Open"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "Men's Raw Open"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "Men's Raw Open"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "Men's Raw Open"

                                                                               "State/Province"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "62.74"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "61.74"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "62.58"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "61.2"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "62.56"
...                                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "81.72"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "81.18"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "82.14"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "80.68"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "82.04"

                                                                                  "Country"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "63"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "63"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "63"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "63"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "63"
...                                                                                     ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "83"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "83"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "83"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "83"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "83"

                                                                                       "Platform"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "1.0773287692485658"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "1.0906031673251644"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "1.0794197564496506"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "1.0979768059215098"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "1.079682006780528"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "0.6737597544301983"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "0.6764993508076719"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "0.671669887265663"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "0.6790899576347297"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0.6721642674003474"

                                                                               "Session"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "37"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "24"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "27"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "29"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "25"
...                                                                                  ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "27"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "21"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "28"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "30"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "30"

                                                                                         "Flight"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "38"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "25"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "28"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "30"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "26"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "27"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "22"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "29"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "31"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "31"

                                                                            ...  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"              ...
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"              ...
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"              ...
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"              ...
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"              ...
...                                                                         ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"              ...
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"              ...
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"              ...
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"              ...
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"              ...

                                                                                          "Total"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "123.61407916828898"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "106.41284286028542"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "105.4715462023794"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "104.8100031030182"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "97.8012543819851"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "72.89908742335024"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "69.2951051782327"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "67.14361626070193"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "63.89589860472197"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                             "Dots Points"         \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "123.61407916828898"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "106.41284286028542"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "105.4715462023794"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "104.8100031030182"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "97.8012543819851"
...                                                                                           ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "72.89908742335024"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "70.68100728179736"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "67.14361626070193"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "63.89589860472197"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                              "Dots & Age Points"   \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "536.942245"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "463.25759999999997"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "458.256"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "456.887"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "425.1085"
...                                                                                            ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "338.94575000000003"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "322.3935"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "311.888"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "297.57"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                    "Wilks Points"        \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "536.942245"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "463.25759999999997"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "458.256"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "456.887"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "425.1085"
...                                                                                                  ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "338.94575000000003"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "328.84137000000004"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "311.888"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "297.57"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                 "Age Points"          \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "467.8177"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "388.848"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "398.49600000000004"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "397.714"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "369.439"
...                                                                                               ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "325.9355"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "309.969"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "299.8255"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "286.104"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                                       "Wilks & Age Points"  \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"               "467.8177"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"               "388.848"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"               "398.49600000000004"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"               "397.714"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"               "369.439"
...                                                                                                     ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"               "325.9355"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"               "316.16838"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"               "299.8255"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"               "286.104"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"               "0"

                                                                            "IPF Points"          \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                           "1"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                           "2"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                           "3"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"                           "4"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"                           "5"
...                                                                                          ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                           "28"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                           "29"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                           "30"
Hao Cheng            "MALE"   "RAW"          ""     "113" "CA"                           "31"
Charles Hammonds     "MALE"   "RAW"          ""     "146" "TX"                           ""

                                                                            "IPF & Age Points"    \
Meghan Scanlon       "FEMALE" "RAW"          ""     "141" "MA"                        "good"
Daisy Arreola Garcia "FEMALE" "RAW"          ""     "138" "OR"                        "good"
Hannah Peterson      "FEMALE" "RAW"          ""     "140" "MN"                        "good"
Sydney Hunter        "FEMALE" "RAW"          ""     "136" "CA"
Maggie Stout         "FEMALE" "RAW"          ""     "137" "MN"
...                                                                                          ...
Benjamin Mathews     "MALE"   "RAW"          ""     "117" "OH"                        "good"
Brandon Flores       "MALE"   "RAW"          ""     "121" "TX"                        "good"
Manasseh Endwarrior  "MALE"   "RAW"          ""     "120" "NM"                        "good"

In [49]:
columns = df.columns
columns = columns.str.replace(' ', '').str.replace('"', '')
columns

Index(['Name', 'Gender', 'Raw/Equipped', 'Team', 'Lot', 'State/Province',
       'Country', 'Platform', 'Session', 'Flight', 'AwardsDivision',
       'BodyWeight(kg)', 'WeightClass', 'WilksCoef', 'ExactAge',
       'DivisionBasedAge', 'AgeCoef', 'Squat1', 'Squat2', 'Squat3',
       'BestSquat', 'Bench1', 'Bench2', 'Bench3', 'BestBench', 'Subtotal',
       'Deadlift1', 'Deadlift2', 'Deadlift3', 'BestDeadlift', 'Total',
       'DotsPoints', 'Dots&AgePoints', 'WilksPoints', 'AgePoints',
       'Wilks&AgePoints', 'IPFPoints', 'IPF&AgePoints', 'GlossbrennerPoints',
       'Glossbrenner&AgePoints'],
      dtype='str')

In [47]:
df.columns = columns
df.head()

,,,,,,Name,Gender,Raw/Equipped,Team,Lot,State/Province,Country,Platform,Session,Flight,...,Total,DotsPoints,Dots&AgePoints,WilksPoints,AgePoints,Wilks&AgePoints,IPFPoints,IPF&AgePoints,GlossbrennerPoints,Glossbrenner&AgePoints
Meghan Scanlon,"""FEMALE""","""RAW""","""""","""141""","""MA""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.74""","""63""","""1.0773287692485658""","""37""","""38""",...,"""123.61407916828898""","""123.61407916828898""","""536.942245""","""536.942245""","""467.8177""","""467.8177""","""1""","""good""","""good""","""good"""
Daisy Arreola Garcia,"""FEMALE""","""RAW""","""""","""138""","""OR""",,"""2""","""4""","""A""","""Women's Raw Open""","""61.74""","""63""","""1.0906031673251644""","""24""","""25""",...,"""106.41284286028542""","""106.41284286028542""","""463.25759999999997""","""463.25759999999997""","""388.848""","""388.848""","""2""","""good""","""good""","""bad"
Hannah Peterson,"""FEMALE""","""RAW""","""""","""140""","""MN""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.58""","""63""","""1.0794197564496506""","""27""","""28""",...,"""105.4715462023794""","""105.4715462023794""","""458.256""","""458.256""","""398.49600000000004""","""398.49600000000004""","""3""","""good""","""good""","""good"""
Sydney Hunter,"""FEMALE""","""RAW""","""""","""136""","""CA""",,"""2""","""4""","""A""","""Women's Raw Open""","""61.2""","""63""","""1.0979768059215098""","""29""","""30""",...,"""104.8100031030182""","""104.8100031030182""","""456.887""","""456.887""","""397.714""","""397.714""","""4""",,,
Maggie Stout,"""FEMALE""","""RAW""","""""","""137""","""MN""",,"""2""","""4""","""A""","""Women's Raw Open""","""62.56""","""63""","""1.079682006780528""","""25""","""26""",...,"""97.8012543819851""","""97.8012543819851""","""425.1085""","""425.1085""","""369.439""","""369.439""","""5""",,,

### transforming using pickle transformation
---

In [ ]:
import csv
import pickle

csv_file = r'data\open_nationals_day_2_awards_results.csv'
pickle_file = r'data\open_nationals_day_2_awards_results.pkl'


try:
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        data_as_list = list(reader) # Read all data into a list

    with open(pickle_file, 'wb') as f: # Open in write binary mode
        pickle.dump(data_as_list, f)
    
    print(f"Successfully converted {csv_file} to a list and saved as {pickle_file} using built-in modules.")

except FileNotFoundError:
    print(f"Error: {csv_file} not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
df = pd.read_pickle(pickle_file)
print(df)

In [ ]:
for x in df:
    print(x)
    print(type(x))

In [ ]:
# TODO: convert list to dicts and input to database with proper column names and types
# stopped because of time needed to convert from csv

# processing data
---
- issue: csv attributes arent completely understood due to the nature of lifting cast
- decision: based on the three sample csvs pulled we will use the columns and indexing seen to retrieve data
- group: data Loading
- assumptions: lifting cast uses the same format for all powerlifting competitions
- constraints: there is data names are slighly different in and due to large amount of potential athletes on the day we could be processing hundreds of athletes very often
- position: using this format we can clean the columns so they always match despite small changes
- implications: pythons naturally slower processing will need to rely on algorithms and optimized time complexity to efficiently process all potential athletes

In [77]:
SAMPLE_LIST =  SAMPLE[0].split(',')
REF_DECISION_INDEX = 42
i = 0
j = 0

DATA = {}
while i < len(COLS):
    if i > REF_DECISION_INDEX and SAMPLE_LIST[j] == 'bad':
        j += 1
        continue
    print(COLS[i], " | ", SAMPLE_LIST[j], "|", i)
    DATA[COLS[i]] = SAMPLE_LIST[j]
    i += 1
    j += 1

Name  |  Meghan Scanlon       | 0
Gender  |   "FEMALE" | 1
Raw/Equipped  |   "RAW"          | 2
Team  |   ""     | 3
Lot  |   "141" | 4
State/Province  |   "MA"             | 5
Country  |             | 6
Platform  |   "2"        | 7
Session  |   "4"       | 8
Flight  |   "A"      | 9
AwardsDivision  |   "Women's Raw Open" | 10
BodyWeight(kg)  |   "62.74"            | 11
WeightClass  |   "63"           | 12
WilksCoef  |   "1.0773287692485658" | 13
ExactAge  |   "37"        | 14
DivisionBasedAge  |   "38"                 | 15
AgeCoef  |   "1"        | 16
Squat1  |   "182.5"   | 17
Squat2  |   "195"     | 18
Squat3  |   "203.5"   | 19
BestSquat  |   "203.5"      | 20
Bench1  |   "132.5"   | 21
Bench2  |   "137.5"   | 22
Bench3  |   "-143.5"  | 23
BestBench  |   "137.5"      | 24
Subtotal  |   "341"      | 25
Deadlift1  |   "192.5"      | 26
Deadlift2  |   "212.5"      | 27
Deadlift3  |   "222.5"      | 28
BestDeadlift  |   "222.5"         | 29
Total  |   "563.5" | 30
DotsPoints  |   "607.5830565145685"  | 31
Dots&AgePoints  |   "607.5830565145685"  | 32
WilksPoints  |   "607.0747614715668"  | 33
AgePoints  |   "563.5"              | 34
Wilks&AgePoints  |   "607.0747614715668"  | 35
IPFPoints  |   "123.61407916828898" | 36
IPF&AgePoints  |   "123.61407916828898" | 37
GlossbrennerPoints  |   "536.942245"          | 38
Glossbrenner&AgePoints  |   "536.942245"                | 39
SchwartzMalonePoints  |   "467.8177"               | 40
SchwartzMalone&AgePoints  |   "467.8177"                     | 41
Place  |   "1"     | 42
S1LRef  |   "good"     | 43
S1HRef  |   "good"     | 44
S1RRef  |   "good"              | 45
S2LRef  |   "good"        | 46
S2HRef  |   "good"        | 47
S2RRef  |   "good"        | 48
S3LRef  |   "good"        | 49
S3HRef  |   "good"        | 50
S3RRef  |   "good"        | 51
B1LRef  |   "good"        | 52
B1HRef  |   "bad | 53
B1RRef  |   red"  | 54
B2LRef  |   "good"        | 55
B2HRef  |   "bad | 56
B2RRef  |   blue"   | 57
B3LRef  |   "good"        | 58
B3HRef  |   "good"        | 59
B3RRef  |   "bad | 60
D1LRef  |   yellow" | 61
D1HRef  |   "bad | 62
D1RRef  |   yellow"       | 63
D2LRef  |   "bad | 64
D2HRef  |   yellow" | 65
D2RRef  |   "good"        | 66
D3LRef  |   "bad | 67
D3HRef  |   yellow" | 68
D3RRef  |   "good"        | 69

In [13]:
print(DATA)

{'Name': 'MeghanScanlon', 'Gender': 'FEMALE', 'Raw/Equipped': 'RAW', 'Team': '', 'Lot': '141', 'State/Province': 'MA', 'Country': '', 'Platform': '2', 'Session': '4', 'Flight': 'A', 'AwardsDivision': "Women'sRawOpen", 'BodyWeight(kg)': '62.74', 'WeightClass': '63', 'WilksCoef': '1.0773287692485658', 'ExactAge': '37', 'DivisionBasedAge': '38', 'AgeCoef': '1', 'Squat1': '182.5', 'Squat2': '195', 'Squat3': '203.5', 'BestSquat': '203.5', 'Bench1': '132.5', 'Bench2': '137.5', 'Bench3': '-143.5', 'BestBench': '137.5', 'Subtotal': '341', 'Deadlift1': '192.5', 'Deadlift2': '212.5', 'Deadlift3': '222.5', 'BestDeadlift': '222.5', 'Total': '563.5', 'DotsPoints': '607.5830565145685', 'Dots&AgePoints': '607.5830565145685', 'WilksPoints': '607.0747614715668', 'AgePoints': '563.5', 'Wilks&AgePoints': '607.0747614715668', 'IPFPoints': '123.61407916828898', 'IPF&AgePoints': '123.61407916828898', 'GlossbrennerPoints': '536.942245', 'Glossbrenner&AgePoints': '536.942245', 'SchwartzMalonePoints': '467.8177', 'SchwartzMalone&AgePoints': '467.8177', 'Place': '1', 'S1LRef': 'good', 'S1HRef': 'good', 'S1RRef': 'good', 'S2LRef': 'good', 'S2HRef': 'good', 'S2RRef': 'good', 'S3LRef': 'good', 'S3HRef': 'good', 'S3RRef': 'good', 'B1LRef': 'good', 'B1HRef': 'red', 'B1RRef': 'good', 'B2LRef': 'blue', 'B2HRef': 'good', 'B2RRef': 'good', 'B3LRef': 'yellow', 'B3HRef': 'yellow', 'B3RRef': 'yellow', 'D1LRef': 'good', 'D1HRef': 'yellow', 'D1RRef': 'good', 'D2LRef': 'good', 'D2HRef': 'good', 'D2RRef': 'good', 'D3LRef': 'good', 'D3HRef': 'good', 'D3RRef': 'good'}

# Database management
---
- issue: planning to move database to free tier cloud service which will require minimal date storage
- decision: we will only store enough data that can help us calculate whats needed as shown in ER_diagram
- group: data Loading
- assumptions: database will allow for enough read writes for all competitions throughout the day (72kb/ large meet)
- constraints: 1GB storage 10GB egress 500mg file storage
- position: can also set up a local database so people can store data on their own which would allow for me not to worry about competitions outside of the selected
- implications: need to set up cloud based database, create ER_diagram, create competition data on server side to minimize database storage

In [14]:
ATTRIBUTES = {'Name', 'Gender', 'Raw/Equipped', 
              'Team', 'Session', 'Flight', 
              'AwardsDivision', 'BodyWeight(kg)', 
              'WeightClass', 'ExactAge', 
              'BestSquat', 'BestBench', 'BestDeadlift'}

# athlete object
---
- issue: unsure if best_lifts are updated as competition progresses or once all three are complete
- decision: process data by choosing the larger successful lift
- group: data Loading
- assumptions: failed lifts seem to be stored as negative numbers so choosing the largest of the 4 should be good using the max function 
- constrains: this might be slow when running frequent scrapes
- position: once best_lift behavior is confirmed we can optimize to the behavior
- implication: due to potential size of competition data keeping time complexity low is a priority

In [15]:
SAMPLE_LIST =  SAMPLE.split(',')
REF_DECISION_INDEX = 42
i = 0
j = 0

DATA = {}
while i < len(COLS):
    if i > REF_DECISION_INDEX and SAMPLE_LIST[j] == 'bad':
        j += 1
        continue
    if COLS[i] in ATTRIBUTES:
        DATA[COLS[i]] = SAMPLE_LIST[j]
    i += 1
    j += 1

print(DATA)

{'Name': 'MeghanScanlon', 'Gender': 'FEMALE', 'Raw/Equipped': 'RAW', 'Team': '', 'Session': '4', 'Flight': 'A', 'AwardsDivision': "Women'sRawOpen", 'BodyWeight(kg)': '62.74', 'WeightClass': '63', 'ExactAge': '37', 'BestSquat': '203.5', 'BestBench': '137.5', 'BestDeadlift': '222.5'}

In [ ]:
def Extract_Athlete(df:pd.DataFrame, path):
    CSV_HEAD = [# personal data
                'Name', 'Gender', 'Raw/Equipped',
                'Team', 'Lot', 'State/Province', 'Country',
                'Platform', 'Session', 'Flight', 'AwardsDivision', 
                'BodyWeight(kg)', 'WeightClass', 'WilksCoef', 
                'ExactAge', 'DivisionBasedAge', 'AgeCoef', 
                # attempted loads
                'Squat1', 'Squat2', 'Squat3', 'BestSquat', 
                'Bench1', 'Bench2', 'Bench3', 'BestBench', 
                'Subtotal', 'Deadlift1', 'Deadlift2', 
                'Deadlift3', 'BestDeadlift', 'Total', 
                # competition scores
                'DotsPoints', 'Dots&AgePoints', 'WilksPoints', 
                'AgePoints', 'Wilks&AgePoints', 'IPFPoints', 
                'IPF&AgePoints', 'GlossbrennerPoints', 
                'Glossbrenner&AgePoints', 'SchwartzMalonePoints', 
                'SchwartzMalone&AgePoints', 'Place', 
                # referee decisions
                'S1LRef', 'S1HRef', 'S1RRef', 'S2LRef', 'S2HRef', 'S2RRef', 'S3LRef', 'S3HRef', 'S3RRef', 
                'B1LRef', 'B1HRef', 'B1RRef', 'B2LRef', 'B2HRef', 'B2RRef', 'B3LRef', 'B3HRef', 'B3RRef', 
                'D1LRef', 'D1HRef', 'D1RRef', 'D2LRef', 'D2HRef', 'D2RRef', 'D3LRef', 'D3HRef', 'D3RRef']
    try:
        df = pd.read_csv(path)
    except:
        # the csv stores , inside referee decisions so we extract manualy
        df = pd.read_csv(path, sep="\t")

In [ ]:
# csv doesnt need any transfomation when the competitions is being 
# scraped ahead of time due to lack of referee decisions

pd2 = pd.read_csv(r'C:\Users\josed\projects\powerliftingCompHandler\notebooks\data\2026_usapl_texas_high_school_state_championships_awards_results.csv')
pd2.head

<bound method NDFrame.head of                  Name  Gender Raw/Equipped                 Team  Lot  \
0       Naudya Garcia  FEMALE     EQUIPPED  Lehman Powerlifting  112
1      Ariza Guerrero  FEMALE     EQUIPPED  Lehman Powerlifting  116
2     Claire Schorsch  FEMALE          RAW           Jourdanton  121
3       Alexa Parrish  FEMALE          RAW           Jourdanton  113
4    Catherine Wooten  FEMALE          RAW                  NaN  118
5       Jaylee Miller  FEMALE          RAW       Vista Ridge HS  119
6        Kristy Yepez  FEMALE          RAW       Vista Ridge HS  122
7          Amaya Loza  FEMALE          RAW           Jourdanton  117
8       Caydee Herbst  FEMALE          RAW           Jourdanton  110
9       Emelia Garcia  FEMALE          RAW           Jourdanton  115
10      Analise Garza  FEMALE          RAW           Jourdanton  123
11   Hayden Schuchman  FEMALE          RAW           Jourdanton  120
12    Nyellie Alcorta  FEMALE          RAW           Jourdanton  111
13     Lianna Olenich  FEMALE          RAW       Vista Ridge HS  114
14     Tavion Feagiai    MALE          RAW       Vista Ridge HS  320
15         Paul Lopez    MALE          RAW           Jourdanton  214
16      Dylan Compere    MALE          RAW                  NaN  218
17    Quentin Trevino    MALE          RAW           Jourdanton  219
18       Zander Hance    MALE          RAW           Jourdanton  215
19      Zak Henderson    MALE          RAW                  NaN  211
20  Alexander Schmeis    MALE          RAW                  NaN  212
21        Ayman Lough    MALE          RAW       Vista Ridge HS  217
22  Sebastian Hoffman    MALE          RAW                  NaN  220
23     Colton Parrish    MALE          RAW           Jourdanton  221
24     Kairo Martinez    MALE          RAW           Jourdanton  213
25    Yeicob Calderon    MALE          RAW                  NaN  216
26      Eric Gonzales    MALE          RAW           Jourdanton  316
27      Abel Gallegos    MALE          RAW           Jourdanton  319
28      Gabe Guerrero    MALE          RAW           Jourdanton  313
29     Tyrell Feagiai    MALE          RAW       Vista Ridge HS  314
30     Benjamin Davis    MALE          RAW        Davis Academy  315
31       Brendan Ruff    MALE          RAW       Terrell Tigers  312
32      Rafe Brewster    MALE          RAW       Vista Ridge HS  311
33       Alek Hillman    MALE          RAW           Jourdanton  210
34      Landen Chavez    MALE          RAW           Jourdanton  310
35        Ethan Shenk    MALE          RAW       Vista Ridge HS  317
36   Caleb Green-Ondo    MALE          RAW           Jourdanton  318
37     Tyrone Feagiai    MALE          RAW       Vista Ridge HS  321
38        Derek Solis    MALE          RAW           Jourdanton  322

   State/Province Country  Platform  Session Flight  ... B3RRef  D1LRef  \
0              TX      US         1        1      A  ...    NaN     NaN
1              TX      US         1        1      A  ...    NaN     NaN
2             NaN     NaN         1        1      A  ...    NaN     NaN
3             NaN     NaN         1        1      A  ...    NaN     NaN
4              TX      US         1        1      A  ...    NaN     NaN
5              TX      US         1        1      A  ...    NaN     NaN
6              TX      US         1        1      A  ...    NaN     NaN
7             NaN     NaN         1        1      A  ...    NaN     NaN
8             NaN     NaN         1        1      A  ...    NaN     NaN
9             NaN     NaN         1        1      A  ...    NaN     NaN
10            NaN     NaN         1        1      A  ...    NaN     NaN
11            NaN     NaN         1        1      A  ...    NaN     NaN
12            NaN     NaN         1        1      A  ...    NaN     NaN
13             TX      US         1        1      A  ...    NaN     NaN
14             TX      US         1        1      C  ...    NaN     NaN
15            NaN     NaN         1        1      B  ...    NaN     NaN
16             TX      US         1        1      B  ...    NaN     NaN
17            NaN     NaN         1        1      B  ...    NaN     NaN
18            NaN     NaN         1        1      B  ...    NaN     NaN
19             TX      US         1        1      B  ...    NaN     NaN
20             TX     NaN         1        1      B  ...    NaN     NaN
21             TX      US         1        1      B  ...    NaN     NaN
22             TX      US         1        1      B  ...    NaN     NaN
23            NaN     NaN         1        1      B  ...    NaN     NaN
24            NaN     NaN         1        1      B  ...    NaN     NaN
25             TX      US         1        1      B  ...    NaN     NaN
26            NaN     NaN         1        1      C  ...    NaN     NaN
27            NaN     NaN         1        1      C  ...    NaN     NaN
28            NaN     NaN         1        1      C  ...    NaN     NaN
29             TX      US         1        1      C  ...    NaN     NaN
30             TX      US         1        1      C  ...    NaN     NaN
31             TX      US         1        1      C  ...    NaN     NaN
32             TX      US         1        1      C  ...    NaN     NaN
33            NaN     NaN         1        1      B  ...    NaN     NaN
34            NaN     NaN         1        1      C  ...    NaN     NaN
35             TX      US         1        1      C  ...    NaN     NaN
36            NaN     NaN         1        1      C  ...    NaN     NaN
37             TX      US         1        1      C  ...    NaN     NaN
38            NaN     NaN         1        1      C  ...    NaN     NaN

   D1HRef  D1RRef  D2LRef  D2HRef  D2RRef  D3LRef  D3HRef  D3RRef
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
5     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
6     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
7     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
8     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
11    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
12    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
13    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
14    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
15    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
16    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
17    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
18    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
19    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
20    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
21    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
22    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
23    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
24    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
25    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
26    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
27    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
28    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
29    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
30    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
31    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
32    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
33    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
34    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
35    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
36    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
37    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
38    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

[39 rows x 70 columns]>